# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_ducks', models.IntegerField(blank=True, default=0, null=True)),
                ('time_fed', models.DateTimeField(auto_now=True)),
                ('food_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.TextField(null=True, verbose_name='Food Type (e.g. Fruits, Vegetables, Meat etc)')),
                ('food_name', models.TextField(null=True, verbose_name='Name of the food')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(default='Canada', verbose_name='Country Name')),
                ('park_name', models.TextField(default='', verbose_name='Park Name')),
            ],
        ),
        migrations.AddField(
            model_name='eventdata',
            name='food_data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duckstatistics.FoodData'),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duckstatistics.Location'),
        ),
    ]
