# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckstatistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='repeat_entry',
            field=models.BooleanField(default=False),
        ),
    ]
